<?php

namespace ContainerSLTq74O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\InvoiceType' shared autowired service.
     *
     * @return \App\Form\InvoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/InvoiceType.php';

        return $container->privates['App\\Form\\InvoiceType'] = new \App\Form\InvoiceType();
    }
}
