<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFOxrxpl\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFOxrxpl/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFOxrxpl.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFOxrxpl\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFOxrxpl\App_KernelTestDebugContainer([
    'container.build_hash' => 'FOxrxpl',
    'container.build_id' => 'c19b6d84',
    'container.build_time' => 1693663389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFOxrxpl');
