<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLTq74O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLTq74O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSLTq74O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSLTq74O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSLTq74O\App_KernelDevDebugContainer([
    'container.build_hash' => 'SLTq74O',
    'container.build_id' => '284db426',
    'container.build_time' => 1693916824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLTq74O');
