<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container425nfDF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container425nfDF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container425nfDF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container425nfDF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container425nfDF\App_KernelDevDebugContainer([
    'container.build_hash' => '425nfDF',
    'container.build_id' => '9f942157',
    'container.build_time' => 1693644699,
], __DIR__.\DIRECTORY_SEPARATOR.'Container425nfDF');
