<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Q0BDyI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Q0BDyI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Q0BDyI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Q0BDyI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3Q0BDyI\App_KernelDevDebugContainer([
    'container.build_hash' => '3Q0BDyI',
    'container.build_id' => 'faf16f90',
    'container.build_time' => 1693649023,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Q0BDyI');
